<?php

// Include the only file of the library.
// There are 5-6 funcs there and their names are not prefixed. But these names are quite unprobable to cause collisions...

 
//how  to use
 





function t_googleurl_libraries_info() {

 

 // A very simple library. No changing APIs (hence, no versions), no variants.
  // Expected to be extracted into 'sites/all/libraries/snoopy'.
  $libraries['googleUrl'] = array(
    'name' => 'googleUrl library',
    'vendor url' => 'https://github.com/t-web/google-url',
    'download url' => 'https://github.com/t-web/google-url',
 
    'version'=> '1.2.4',
    'files' => array(
      'php' => array(
      'autoload.php',

      ), //this can be a path to the file location like array('lib/simple.js')
    ),
  );

  return $libraries;



}





// $l=t_googleurl__google_search("qq",'10','0');
// print_r($l);
// 
// 
// 
// 
function t_googleurl_google_search($keyword,$num='10',$page='0'){
if (($library = libraries_load("googleUrl")) && !empty($library['loaded'])) {
  // Do something with the library here.
  // 
  //echo 'jiazia';



$googleUrl=new \GoogleUrl();
        $googleUrl->setLang('en') // lang allows to adapt the query (tld, and google local params)
            ->setNumberResults($num);                        // 10 results per page
     //   $acdcPage1=$googleUrl->setPage(0)->search("acdc"); // acdc results page 1 (results 1-10)
    //    $acdcPage2=$googleUrl->setPage(1)->search("acdc"); // acdc results page 2 (results 11-20)

        //$googleUrl->setNumberResults(100);
        $simpsonPage1=$googleUrl->setPage($page)->search($keyword); // simpsons results page 1 (results 1-20)

        // GET NATURAL RESULTS

        $positions=$simpsonPage1->getPositions();

      //  echo "results for " . $simpsonPage1->getKeywords();
   //     echo "<ul>";
        foreach($positions as $result){


  $link[id]=$result->getPosition();
    $link[title]=utf8_decode($result->getTitle());
   $link[url]=$result->getUrl() ;


   $links[]=$link;
// print_r($result);

   //          echo "<li>";
   //          echo "<ul>";
   //          echo "<li>position : " . $result->getPosition() . "</li>";
   //          echo "<li>title : "    . utf8_decode($result->getTitle())    . "</li>";
   //          echo "<li>website : "  . $result->getWebsite()  . "</li>";
   //          echo "<li>URL : <a href='" . $result->getUrl() ."'>" . $result->getUrl() . "</a></li>";
   //     echo "<li>link : "    . utf8_decode($result->getSnippet())    . "</li>";
   //        echo "<li>title : "    . utf8_decode($result->getPosition())    . "</li>";
   // echo "<li>title : "    . utf8_decode($result->getTitle())    . "</li>";
   //    echo "<li>title : "    . utf8_decode($result->getTitle())    . "</li>";



   //          echo "</ul>";
   //          echo "</li>";
        }
        //echo "</ul>";


return $links;




}else{

  echo $library["error message"];
}
}



 