<?php

// Include the only file of the library.
// There are 5-6 funcs there and their names are not prefixed. But these names are quite unprobable to cause collisions...

 
//how  to use
 





function t_googleurl_libraries_info() {

 

 // A very simple library. No changing APIs (hence, no versions), no variants.
  // Expected to be extracted into 'sites/all/libraries/snoopy'.
  $libraries['googleUrl'] = array(
    'name' => 'googleUrl library',
    'vendor url' => 'https://github.com/t-web/Snoopy',
    'download url' => 'https://github.com/t-web/Snoopy',
 
    'version'=> '1.2.4',
    'files' => array(
      'php' => array(
      'autoload.php',

      ), //this can be a path to the file location like array('lib/simple.js')
    ),
  );

  return $libraries;



}
 